import '../service/jenis_catatan_service.dart';
import '../model/jenis_catatan_model.dart';

class JenisCatatanRepository {
  final service = JenisCatatanService();

  Future<List<JenisCatatan>> getByTipe(String tipe) async {
    try {
      final data = await service.getByTipe(tipe);

      if (data.isEmpty) {
        print("⚠️ Data kosong untuk tipe: $tipe");
        return [];
      }

      // Parse data
      return data.map<JenisCatatan>((e) {
        try {
          return JenisCatatan.fromJson(e);
        } catch (e) {
          print("❌ Error parsing item: $e");
          print("📦 Item yang gagal: $e");
          rethrow;
        }
      }).toList();
    } catch (e) {
      print("❌ Error di Repository: $e");
      rethrow;
    }
  }

  Future<bool> addJenisCatatan(JenisCatatan item) async {
    try {
      final Map<String, dynamic> data = item.toJson();
      data.remove('id'); // ID is generated by database
      return await service.addJenisCatatan(data);
    } catch (e) {
      print("❌ Error di Repository addJenisCatatan: $e");
      rethrow;
    }
  }

  Future<bool> updateJenisCatatan(JenisCatatan item) async {
    try {
      if (item.id == null) throw Exception("ID tidak boleh null untuk update");
      final Map<String, dynamic> data = item.toJson();
      return await service.updateJenisCatatan(item.id!, data);
    } catch (e) {
      print("❌ Error di Repository updateJenisCatatan: $e");
      rethrow;
    }
  }

  Future<bool> deleteJenisCatatan(int id) async {
    try {
      return await service.deleteJenisCatatan(id);
    } catch (e) {
      print("❌ Error di Repository deleteJenisCatatan: $e");
      rethrow;
    }
  }
}
